### ISSUE TITLE
credit card holder name

### ISSUE THREAD

**Issue by fritzek** [travis-ci/travis-crowd#2] opened 2012-01-05 12:39 UTC
we need a separate field for the card holder name as it could defer from the users name (in strip the field is empty and marked as "not provided")
if stripe says it doesn't matter, close the issue

**Comment by svenfuchs** [comment] 2012-01-06 14:43
done. let's hope this works, the docs aren't super clear on this

**Comment by fritzek** [comment] 2012-01-06 16:04
tried it with a new user and get a 500

**Comment by svenfuchs** [comment] 2012-01-06 16:07
you said it didn't submit the form, which issue should be resolved.

is that https://github.com/travis-ci/travis-crowd/issues/17 ?

**Comment by fritzek** [comment] 2012-01-06 16:10
with this issue you've addressed the separate card holder name field and i've tried to make a subscription for a new user (I was not signed in)

**Comment by svenfuchs** [comment] 2012-01-06 16:15
when you submit the form with credit card fields (i.e not signed in) then it will first submit the credit card info to Stripe directly. it then get's a credit card token back that is inserted to a hidden field in our form. this form is then sent to our app.

i.e if you get a 500 that's an error on our app. i.e. the credit card field processing has succeeded. i.e. i guess the remaining issue here is a duplicate of #17, right?

**Comment by fritzek** [comment] 2012-01-06 16:23
tried again with different card and it worked (before I used the same card as before for another user) so you could be right that this duplicate to #17 (if card info is part of our models)

**Comment by fritzek** [comment] 2012-01-06 16:34
hm, said before that with a new card it worked. this was just half of the truth - our side behaved as the payment was successful processed, but I can't see the payment in stripe and the landing page doesn't show it neither.

**Comment by svenfuchs** [comment] 2012-01-06 20:23
it's kinda hard to guess what exactly you've done. there are various things that could go wrong. could you plz test again and open a new ticket with the behaviour/error?

**Closed as completed by svenfuchs** 2012-01-06 20:23 UTC
